### ISSUE TITLE
Adding docker labels has broken the ability to launch via docker-compose (inc the web UI)

### ISSUE THREAD

**Issue by GlennPegden2** [GlennPegden2/RetroNetSec#9]
Even though it seems to be using docker-compose labels the correct way (and parses as valid yaml) the addition of labels seems to have broken the ability to launch via docker-compose, it looks to fail some linting test

**Comment by WorpDress** [comment]
Fixed

Though in doing so, it’s lost the ability to specify more than one user-supplied Img in the docker-compose.yank

**Comment by GlennPegden2** [comment]
Ooops, wrong account

Fixed
